### ISSUE TITLE
main() async produces Uninitialized Module.DEFAULT_REFLECTOR error

### ISSUE THREAD

**Issue by MikeMitterer** [angular/di.dart#221]
This fails:
```dartlang
main() async {
    final MaterialApplication app = await componentFactory().rootContext(Application)
        .addModule(new SampleModule()).run();
    app.run();
}
```
but this works!!!!!
```dartlang
main() {
    componentFactory().rootContext(Application).addModule(new SampleModule()).run()
    .then( (final MaterialApplication application) {
        application.run();
    });
}
```

**Comment by matanlurey** [comment]
You need to add the module before awaiting.

```
await (componentFactory().rootContext(Application).addModule(new SampleModule())).run();
```

**Comment by MikeMitterer** [comment]
What do you mean with "add the module"? run() is the last function in the chain. Run returns Future<MaterialApplication> - this has nothing todo with the module. It's definitely the "async" keyword that produces the error.

**Comment by kegluneq** [comment]
This appears to be an issue with how the `di` transformer is using `package:analyzer` to rewrite the entry point.

A simple repro:

web/main.dart
```
library main;

import 'dart:async';

main() async {
  print('hello');
}
```

pubspec.yaml
```
name: test
dependencies:
  di: any
transformers:
- di
```

If I `print(printer.text)` [here](https://github.com/angular/di.dart/blob/master/lib/transformer/injector_generator.dart#L389), this is the result:

```
library main;

import 'dart:async';
import 'main_generated_type_factory_maps.dart' show setStaticReflectorAsDefault;

main() async
  setStaticReflectorAsDefault(); {
  print('hello');
}
```
